theme = "catppuccin_macchiato"

[editor]
scroll-lines = 1
cursorline = true
auto-save = false
completion-trigger-len = 1
true-color = true
color-modes = true
auto-pairs = true
rulers = [80]
idle-timeout = 50
auto-format = true
trim-trailing-whitespace = true
insert-final-newline = true

[editor.file-picker]
git-ignore = false
hidden = false
follow-symlinks = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "|"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.soft-wrap]
enable = true

[editor.statusline]
left = [
  "mode",
  "spinner",
  "file-name",
  "file-type",
  "total-line-numbers",
  "file-encoding",
]
center = []
right = [
  "selections",
  "primary-selection-length",
  "position",
  "position-percentage",
  "spacer",
  "diagnostics",
  "workspace-diagnostics",
  "version-control",
]

[keys.normal]
C-r = ":reload"
C-R = ":reload-all"
C-h = "goto_previous_buffer"
C-l = "goto_next_buffer"
C-w = ":buffer-close"
C-s = ":hsplit"
C-v = ":vsplit"
