[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.ruff-lsp]
command = "ruff-lsp"

[language-server.gopls]
command = "gopls"

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.terraform-ls]
command = "terraform-ls"
args = ["serve"]

[language-server.yaml-language-server]
command = "yaml-language-server"
args = ["--stdio"]

[language-server.vscode-json-language-server]
command = "vscode-json-language-server"
args = ["--stdio"]

[language-server.marksman]
command = "marksman"

[language-server.taplo]
command = "taplo"
args = ["lsp", "stdio"]

[language-server.bash-language-server]
command = "bash-language-server"
args = ["start"]

[language-server.docker-langserver]
command = "docker-langserver"
args = ["--stdio"]

[language-server.sqls]
command = "sqls"

[language-server.lua-language-server]
command = "lua-language-server"

[[language]]
name = "python"
language-servers = ["ruff-lsp", "pyright"]
auto-format = true
formatter = { command = "ruff", args = ["format", "-"] }

[[language]]
name = "go"
language-servers = ["gopls"]
auto-format = true
formatter = { command = "gofumpt" }

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
auto-format = true
formatter = { command = "rustfmt", args = ["--emit=stdout"] }

[[language]]
name = "terraform"
language-servers = ["terraform-ls"]
auto-format = true
formatter = { command = "terraform", args = ["fmt", "-"] }

[[language]]
name = "yaml"
language-servers = ["yaml-language-server"]
auto-format = true
formatter = { command = "prettier", args = ["--parser", "yaml"] }

[[language]]
name = "json"
language-servers = ["vscode-json-language-server"]
auto-format = true
formatter = { command = "prettier", args = ["--parser", "json"] }

[[language]]
name = "markdown"
language-servers = ["marksman"]
auto-format = true
formatter = { command = "prettier", args = ["--parser", "markdown"] }

[[language]]
name = "toml"
language-servers = ["taplo"]
auto-format = true
formatter = { command = "taplo", args = ["format", "-"] }

[[language]]
name = "bash"
language-servers = ["bash-language-server"]
auto-format = true
formatter = { command = "shfmt", args = ["-i", "2", "-bn", "-ci"] }

[[language]]
name = "dockerfile"
language-servers = ["docker-langserver"]

[[language]]
name = "sql"
language-servers = ["sqls"]

[[language]]
name = "lua"
language-servers = ["lua-language-server"]
auto-format = true
formatter = { command = "stylua", args = ["-"] }

