# Font
font_family      JetBrainsMono NF Regular
font_size        13
disable_ligatures never

# Theme
include current-theme.conf

# Key mappings
map alt+backspace send_text all \x1b\x7f
map shift+enter   send_text all \n

# macOS
macos_quit_when_last_window_closed yes
