# Font
font_family      JetBrainsMono NF Regular
font_size        13
disable_ligatures always

# Key mappings
map alt+backspace send_text all \x1b\x7f
map shift+enter   send_text all \n

# Splits
enabled_layouts splits,stack
map cmd+d        launch --location=vsplit --cwd=current
map cmd+shift+d  launch --location=hsplit --cwd=current
map cmd+]        neighboring_window right
map cmd+[        neighboring_window left
map cmd+shift+enter toggle_layout stack

# macOS
macos_quit_when_last_window_closed yes


# BEGIN_KITTY_THEME
# Solarized Darcula
include current-theme.conf
# END_KITTY_THEME