# Font
font_family      JetBrainsMono NF Regular
font_size        13
disable_ligatures never

# Layouts
enabled_layouts splits,stack

# Key mappings
map alt+backspace send_text all \x1b\x7f
map shift+enter   send_text all \n

# Splits
map cmd+d        launch --location=vsplit --cwd=current
map cmd+shift+d  launch --location=hsplit --cwd=current
map cmd+alt+left   neighboring_window left
map cmd+alt+right  neighboring_window right
map cmd+alt+up     neighboring_window up
map cmd+alt+down   neighboring_window down
map cmd+w close_window

# Zoom (toggle stack layout)
map cmd+shift+return toggle_layout stack

# macOS
macos_quit_when_last_window_closed yes


# BEGIN_KITTY_THEME
# Solarized Darcula
include current-theme.conf
# END_KITTY_THEME