[helpers]

[atuin.files]
atuin = "~/.config/atuin/config.toml"

[atuin.variables]
filter_mode = "global"
style = "full"

[git.files]
gitconfig = "~/.gitconfig"
gitconfig-work = "~/.gitconfig.work"

[git.variables]
work_email = ""

[tmux.files]
tmux = "~/.tmux.conf"
tmuxinator-home = "~/.config/tmuxinator/home.yml"

[nvim.files]
nvim = "~/.config/nvim"

[vim.files]
vimrc = "~/.config/nvim/init.vim"

[zsh.files]
zshrc = "~/.zshrc"

