[helpers]

[shell.files]
atuin = "~/.config/atuin/config.toml"
bat = "~/.config/bat/config"
gitconfig = "~/.gitconfig"
gitconfig-work = "~/.gitconfig.work"
tmux = "~/.tmux.conf"
tmuxinator-home = "~/.config/tmuxinator/home.yml"
zshrc = "~/.zshrc"

[shell.variables]
filter_mode = "global"
style = "full"
work_email = ""

[nvim.files]
nvim = "~/.config/nvim"

[vim.files]
vimrc = "~/.config/nvim/init.vim"
